// Export pages
export '/modulo_autenticacion/login/login_widget.dart' show LoginWidget;
export '/modulo_rutinas/home_rutinas/home_rutinas_widget.dart'
    show HomeRutinasWidget;
export '/modulo_inicio/home_page/home_page_widget.dart' show HomePageWidget;
export '/modulo_actividades/actividades/actividades_widget.dart'
    show ActividadesWidget;
export '/modulo_rutinas/ejercicios/ejercicios_widget.dart'
    show EjerciciosWidget;
export '/modulo_autenticacion/registro/registro_widget.dart'
    show RegistroWidget;
export '/modulo_actividades/calendario_actividades/calendario_actividades_widget.dart'
    show CalendarioActividadesWidget;
export '/modulo_tienda/home_shop/home_shop_widget.dart' show HomeShopWidget;
export '/modulo_tienda/suplementos/supplements/supplements_widget.dart'
    show SupplementsWidget;
export '/modulo_administrador/modulo_admin_actividades/registrar_actividades/registrar_actividades_widget.dart'
    show RegistrarActividadesWidget;
export '/modulo_administrador/modulo_admin_actividades/cancelar_actividades/cancelar_actividades_widget.dart'
    show CancelarActividadesWidget;
export '/modulo_administrador/modulo_admin_actividades/administrar_actividades/administrar_actividades_widget.dart'
    show AdministrarActividadesWidget;
export '/modulo_administrador/modulo_admin_tienda/home_shop_admin/home_shop_admin_widget.dart'
    show HomeShopAdminWidget;
export '/modulo_administrador/modulo_admin_tienda/modulo_admin_zapatos/add_shoes/add_shoes_widget.dart'
    show AddShoesWidget;
export '/modulo_administrador/modulo_admin_rutinas/admin_home_rutinas/admin_home_rutinas_widget.dart'
    show AdminHomeRutinasWidget;
export '/modulo_administrador/modulo_admin_rutinas/crear_home_rutina/crear_home_rutina_widget.dart'
    show CrearHomeRutinaWidget;
export '/modulo_administrador/modulo_admin_rutinas/crear_ejercicio/crear_ejercicio_widget.dart'
    show CrearEjercicioWidget;
export '/modulo_administrador/modulo_admin_tienda/modulo_admin_zapatos/editar_zapato/editar_zapato_widget.dart'
    show EditarZapatoWidget;
export '/modulo_administrador/modulo_admin_tienda/modulo_admin_suplementos/editar_suplemento/editar_suplemento_widget.dart'
    show EditarSuplementoWidget;
export '/modulo_administrador/modulo_admin_tienda/modulo_admin_suplementos/add_supplement/add_supplement_widget.dart'
    show AddSupplementWidget;
export '/modulo_nutricionista/home_nutricionista/home_nutricionista_widget.dart'
    show HomeNutricionistaWidget;
export '/modulo_nutricionista/info_nutricionista/info_nutricionista_widget.dart'
    show InfoNutricionistaWidget;
export '/modulo_nutricionista/medidas/medidas_widget.dart' show MedidasWidget;
export '/borrador/borradorhome/borradorhome_widget.dart'
    show BorradorhomeWidget;
export '/modulo_entrenador/home_entrenador/home_entrenador_widget.dart'
    show HomeEntrenadorWidget;
export '/modulo_entrenador/perfil_entrenador/perfil_entrenador_widget.dart'
    show PerfilEntrenadorWidget;
export '/modulo_perfil/perfil_usuario/perfil_usuario_widget.dart'
    show PerfilUsuarioWidget;
export '/modulo_administrador/modulo_admin_nutricionista/editar_medidas/editar_medidas_widget.dart'
    show EditarMedidasWidget;
export '/modulo_administrador/modulo_admin_nutricionista/bucar_medidas/bucar_medidas_widget.dart'
    show BucarMedidasWidget;
export '/modulo_administrador/modulo_admin_rutinas/admin_ejercicios/admin_ejercicios_widget.dart'
    show AdminEjerciciosWidget;
export '/modulo_administrador/modulo_admin_entrenador/crear_entrenador/crear_entrenador_widget.dart'
    show CrearEntrenadorWidget;
export '/modulo_administrador/modulo_admin_entrenador/home_admin_entrenador/home_admin_entrenador_widget.dart'
    show HomeAdminEntrenadorWidget;
export '/modulo_administrador/modulo_admin_entrenador/editar_entrenadores/editar_entrenadores_widget.dart'
    show EditarEntrenadoresWidget;
export '/modulo_administrador/modulo_admin_perfil/admin_perfil/admin_perfil_widget.dart'
    show AdminPerfilWidget;
export '/modulo_administrador/modulo_admin_tienda/modulo_admin_suplementos/admin_supplements/admin_supplements_widget.dart'
    show AdminSupplementsWidget;
export '/modulo_administrador/modulo_admin_tienda/modulo_admin_zapatos/admin_zapatos/admin_zapatos_widget.dart'
    show AdminZapatosWidget;
export '/modulo_administrador/modulo_admin_perfil/admin_usuarios/admin_usuarios_widget.dart'
    show AdminUsuariosWidget;
export '/modulo_tienda/zapatos/shoes/shoes_widget.dart' show ShoesWidget;
